version: "3"

services:
    www:
        build: ./image_www
        image: seed-image-www-sqli
        container_name: www-10.9.0.5
        tty: true
        volumes:
            - ./image_www/Code:/var/www/html        
        ports:
            - "3128:80"
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5
        #command: bash -c "chmod 777 /var/www/html/comments.txt"

    mysql:
        build: ./image_mysql
        image: seed-image-mysql-sqli
        container_name: mysql-10.9.0.6
        command: --default-authentication-plugin=mysql_native_password
        tty: true
        restart: always
        cap_add:
                - SYS_NICE  # CAP_SYS_NICE (surprise an error message)
        volumes:
                - ./mysql_data:/var/lib/mysql
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6
    attack:
        build: ./attacker
        image: attacker-image
        container_name: attacker
        tty: true
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.2  
networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

